// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_PwrS0yxk1mStx-Ky2q1bplfhZ3Hufw',
    appId: '1:687909741259:web:a578ffbccba34e1ae9f14e',
    messagingSenderId: '687909741259',
    projectId: 'managedata-8f6f9',
    authDomain: 'managedata-8f6f9.firebaseapp.com',
    storageBucket: 'managedata-8f6f9.firebasestorage.app',
    measurementId: 'G-RQGVTTPP0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQGPWgN7swWu9S1KOIjf256iv8RtzHT0',
    appId: '1:687909741259:android:98029350f83ec1f4e9f14e',
    messagingSenderId: '687909741259',
    projectId: 'managedata-8f6f9',
    storageBucket: 'managedata-8f6f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEP-cn32gl62dJNh8_UuBI7QOJac6XIHk',
    appId: '1:687909741259:ios:fb1427659335f442e9f14e',
    messagingSenderId: '687909741259',
    projectId: 'managedata-8f6f9',
    storageBucket: 'managedata-8f6f9.firebasestorage.app',
    iosBundleId: 'com.example.manageData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEP-cn32gl62dJNh8_UuBI7QOJac6XIHk',
    appId: '1:687909741259:ios:fb1427659335f442e9f14e',
    messagingSenderId: '687909741259',
    projectId: 'managedata-8f6f9',
    storageBucket: 'managedata-8f6f9.firebasestorage.app',
    iosBundleId: 'com.example.manageData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_PwrS0yxk1mStx-Ky2q1bplfhZ3Hufw',
    appId: '1:687909741259:web:48c354c38d9e83c0e9f14e',
    messagingSenderId: '687909741259',
    projectId: 'managedata-8f6f9',
    authDomain: 'managedata-8f6f9.firebaseapp.com',
    storageBucket: 'managedata-8f6f9.firebasestorage.app',
    measurementId: 'G-EVTG7XTVVF',
  );
}
